#Auto generated by FuseSoC

DESIGN_NAME := de10-nano-bus-spider_0
QUARTUS_OPTIONS := --64bit

qsys:
	ip-generate --project-directory=../src/de10-nano-bus-spider_0/data --output-directory=qsys/soc_system --report-file=bsf:qsys/soc_system/soc_system.bsf --system-info=DEVICE_FAMILY="Cyclone V" --system-info=DEVICE=5CSEBA6U23I7 --component-file=../src/de10-nano-bus-spider_0/data/soc_system.qsys
	ip-generate --project-directory=../src/de10-nano-bus-spider_0/data --output-directory=qsys/soc_system/synthesis --file-set=QUARTUS_SYNTH --report-file=sopcinfo:qsys/soc_system/soc_system.sopcinfo --report-file=html:qsys/soc_system/soc_system.html --report-file=qip:qsys/soc_system/soc_system.qip --report-file=cmp:qsys/soc_system/soc_system.cmp --report-file=svd --system-info=DEVICE_FAMILY="Cyclone V" --system-info=DEVICE=5CSEBA6U23I7 --component-file=../src/de10-nano-bus-spider_0/data/soc_system.qsys --language=VERILOG
