project_new de10-nano-bus-spider_0 -overwrite
set_global_assignment -name FAMILY "Cyclone V"
set_global_assignment -name DEVICE 5CSEBA6U23I7
set_global_assignment -name TOP_LEVEL_ENTITY de10_nano_bus_spider
set_global_assignment -name VERILOG_FILE ../src/altera_clkgen_0/wrapped_altpll.v
set_global_assignment -name VERILOG_FILE ../src/altera_clkgen_0/altpll_wb_clkgen.v
set_global_assignment -name VERILOG_FILE ../src/altera_clkgen_0/wrapped_altera_pll.v
set_global_assignment -name VERILOG_FILE ../src/altera_clkgen_0/altera_pll_wb_clkgen.v
set_global_assignment -name VERILOG_FILE ../src/gpio_0/gpio.v
set_global_assignment -name VERILOG_FILE ../src/or1k_bootloaders_0.9/wb_bootrom.v
set_global_assignment -name VERILOG_FILE ../src/picorv32_0/axi4_memory.v
set_global_assignment -name VERILOG_FILE ../src/picorv32_0/picorv32.v
set_global_assignment -name VERILOG_FILE ../src/picorv32_0/picorv32_top.v
set_global_assignment -name VERILOG_FILE ../src/uart16550_1.5.4/rtl/verilog/raminfr.v
set_global_assignment -name VERILOG_FILE ../src/uart16550_1.5.4/rtl/verilog/uart_receiver.v
set_global_assignment -name VERILOG_FILE ../src/uart16550_1.5.4/rtl/verilog/uart_regs.v
set_global_assignment -name VERILOG_FILE ../src/uart16550_1.5.4/rtl/verilog/uart_rfifo.v
set_global_assignment -name VERILOG_FILE ../src/uart16550_1.5.4/rtl/verilog/uart_sync_flops.v
set_global_assignment -name VERILOG_FILE ../src/uart16550_1.5.4/rtl/verilog/uart_tfifo.v
set_global_assignment -name VERILOG_FILE ../src/uart16550_1.5.4/rtl/verilog/uart_top.v
set_global_assignment -name VERILOG_FILE ../src/uart16550_1.5.4/rtl/verilog/uart_transmitter.v
set_global_assignment -name VERILOG_FILE ../src/uart16550_1.5.4/rtl/verilog/uart_wb.v
set_global_assignment -name VERILOG_FILE ../src/verilog-arbiter_0-r1/src/arbiter.v
set_global_assignment -name VERILOG_FILE ../src/wb_intercon_1.0/rtl/verilog/wb_arbiter.v
set_global_assignment -name VERILOG_FILE ../src/wb_intercon_1.0/rtl/verilog/wb_data_resize.v
set_global_assignment -name VERILOG_FILE ../src/wb_intercon_1.0/rtl/verilog/wb_upsizer.v
set_global_assignment -name VERILOG_FILE ../src/wb_intercon_1.0/rtl/verilog/wb_mux.v
set_global_assignment -name VERILOG_FILE ../src/wb_ram_1.0/rtl/verilog/wb_ram.v
set_global_assignment -name VERILOG_FILE ../src/bus-spider-soc_0/rtl/verilog/picorv32-wb-soc.v
set_global_assignment -name VERILOG_FILE ../src/bus-spider-soc_0/rtl/verilog/wb_intercon/wb_intercon.v
set_global_assignment -name VERILOG_FILE ../src/de10-nano-bus-spider_0/rtl/verilog/de10-nano-bus-spider.v
set_global_assignment -name QIP_FILE qsys/soc_system/soc_system.qip
set_global_assignment -name SDC_FILE ../src/de10-nano-bus-spider_0/data/de10-nano-bus-spider.sdc
source ../src/de10-nano-bus-spider_0/data/de10-nano-bus-spider.qsf
set_global_assignment -name SEARCH_PATH ../src/or1k_bootloaders_0.9
set_global_assignment -name SEARCH_PATH ../src/riscv-nmon_0
set_global_assignment -name SEARCH_PATH ../src/uart16550_1.5.4/rtl/verilog
set_global_assignment -name SEARCH_PATH ../src/verilog_utils_0
set_global_assignment -name SEARCH_PATH ../src/wb_common_0
set_global_assignment -name SEARCH_PATH ../src/bus-spider-soc_0/rtl/verilog/wb_intercon
